######################
# Common parts
# ####################
EXECUTABLE: dxrt-cli

CURRENT_VERSIONS:
  DX_RT: v3.0.0
  RT_DRIVER: v1.7.1
  PCIE_DRIVER: v1.4.1
  FIRMWARE: v2.1.4
  DX_TOP: v1.0.0

MINIMUM_VERSIONS:
  FIRMWARE: v2.1.0
  COMPILER: v1.18.1
  DXNN_FORMAT: "v6"

FIRMWARE_FILES:
  LATEST: dx_fw/m1/2.1.4/mdot2/fw.bin
  OLD:    dx_fw/m1/2.1.0/mdot2/fw.bin


#####################
# Each TC
# ###################
runmodel_help_required:
  - "-m, --model"
  - "-i, --input"
  - "-o, --output"
  - "-b, --benchmark"
  - "-s, --single"
  - "-v, --verbose"
  - "-n, --npu"
  - "-l, --loops"
  - "-t, --time"
  - "-d, --devices"
  - "-f, --fps"
  - "--skip-io"
  - "--use-ort"
  - "-h, --help"

runmodel_benchmark:
  default_model_path: workspace/res/models/models-2_0_0/YoloV7.dxnn

python_package:
  venv_python: "venv-dx-runtime"
