######################
# Common parts
######################
dx_com_path: "dx_com/dx_com/dx_com"

#####################
# Each TC
#####################
getting_start:
  step1: getting-start/compiler-1_download_onnx.sh
  step2: getting-start/compiler-2_setup_calibration_dataset.sh
  step3: getting-start/compiler-3_setup_output_path.sh
  step4: getting-start/compiler-4_model_compile.sh

basic_cmd:
  cmd1: dx_com/dx_com -m sample/MobileNetV1-1.onnx -c sample/MobileNetV1-1.json -o output/MobileNetV1
  out1: output/MobileNetV1/MobileNetV1-1.dxnn
  cmd2: dx_com/dx_com -m sample/ResNet50-1.onnx -c sample/ResNet50-1.json -o output/ResNet50-1
  out2: output/ResNet50-1/ResNet50-1.dxnn
  cmd3: dx_com/dx_com -m sample/YOLOV5-1.onnx -c sample/YOLOV5-1.json -o output/YOLOV5-1
  out3: output/YOLOV5-1/YOLOV5-1.dxnn
  timeout: 180 # ResNet50 compile time < 3 mins
  logfile: output/MobileNetV1/main_log.bin
  dxnn_format_version: v7
  compiler_version: v2.0.0

dx_com_info: |
  dx_codegen  : 2.33.1
  dx_com      : 2.0.0
  dx_common   : 0.60.0
